In [3]:
import numpy as np

#Operations on a 3x3 matrix
matrix_3x3 = np.array([[3, 6, 9], [12, 15, 18], [21, 24, 27]])
mean_3x3 = matrix_3x3.mean()  # Calculate mean of all elements
variance_3x3 = matrix_3x3.var()  # Calculate variance of all elements
std_dev_3x3 = matrix_3x3.std()  # Calculate standard deviation of all elements
mean_columns_3x3 = matrix_3x3.mean(axis=0)  # Calculate mean of each column



In [6]:
# Print results
print("Task 1 Results:")
print("Mean:", mean_3x3)
print("Variance:", variance_3x3)
print("Standard Deviation:", std_dev_3x3)
print("Mean of each column:", mean_columns_3x3)


Task 1 Results:
Mean: 15.0
Variance: 60.0
Standard Deviation: 7.745966692414834
Mean of each column: [12. 15. 18.]


In [4]:
#Manipulate a 4x3 matrix
matrix_4x3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]])
reshaped_2_6 = matrix_4x3.reshape(2, 6)  # Reshape the matrix to 2 rows and 6 columns
size_4x3 = matrix_4x3.size  # Get the total number of elements
reshaped_1_row = matrix_4x3.reshape(1, -1)  # Reshape to 1 row with as many columns as needed
transpose_4x3 = matrix_4x3.T  # Transpose the matrix
flattened_4x3 = matrix_4x3.flatten()  # Flatten the matrix to a 1D array
det_4x3 = np.linalg.det(matrix_4x3[:3, :3])  # Calculate determinant of the first 3x3 part
diagonal_4x3 = np.diagonal(matrix_4x3[:3, :3])  # Extract the main diagonal
diagonal_above_4x3 = np.diagonal(matrix_4x3[:3, :3], 1)  # Extract one above the main diagonal
diagonal_below_4x3 = np.diagonal(matrix_4x3[:3, :3], -1)  # Extract one below the main diagonal



In [7]:
print("\nTask 2 Results:")
print("Reshaped to 2x6:", reshaped_2_6)
print("Size of matrix:", size_4x3)
print("Reshaped to 1 row:", reshaped_1_row)
print("Transpose:", transpose_4x3)
print("Flattened:", flattened_4x3)
print("Determinant:", det_4x3)
print("Diagonal elements:", diagonal_4x3)
print("Diagonal above main:", diagonal_above_4x3)
print("Diagonal below main:", diagonal_below_4x3)



Task 2 Results:
Reshaped to 2x6: [[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]]
Size of matrix: 12
Reshaped to 1 row: [[ 10  20  30  40  50  60  70  80  90 100 110 120]]
Transpose: [[ 10  40  70 100]
 [ 20  50  80 110]
 [ 30  60  90 120]]
Flattened: [ 10  20  30  40  50  60  70  80  90 100 110 120]
Determinant: -4.263256414560599e-12
Diagonal elements: [10 50 90]
Diagonal above main: [20 60]
Diagonal below main: [40 80]


In [5]:
# Operations between two 3x3 matrices
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
addition_a_b = np.add(matrix_a, matrix_b)  # Add two matrices
subtraction_a_b = np.subtract(matrix_a, matrix_b)  # Subtract matrix_b from matrix_a
multiplication_a_b = np.dot(matrix_a, matrix_b)  # Multiply two matrices



In [8]:


print("\nTask 3 Results:")
print("Addition of A and B:", addition_a_b)
print("Subtraction of B from A:", subtraction_a_b)
print("Multiplication of A with B:", multiplication_a_b)



Task 3 Results:
Addition of A and B: [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction of B from A: [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Multiplication of A with B: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
