# NumPy


In [2]:
import numpy as np

A = np.array([[1, 1, 1],
              [6, 4, 5],
              [5, 2, 2]])

b = np.array([2, 31, 13])


In [ ]:
print(A)
print(A.shape)
print(b.dtype)

[[1 1 1]
 [6 4 5]
 [5 2 2]]
(3, 3)
int64


In [ ]:
A + A

array([[ 2,  2,  2],
       [12,  8, 10],
       [10,  4,  4]])

In [ ]:
A - A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
A * 2

array([[ 2,  2,  2],
       [12,  8, 10],
       [10,  4,  4]])

Consider the performance at some scale

In [ ]:
#create two objects for comparison one numpy the other a list
my_arr = np.arange(1000000)

my_list = list(range(1000000))

In [ ]:
# multiply by a scalar
%timeit my_arr2 = my_arr * 2

1.03 ms ± 65.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
%timeit my_list2 = [x * 2 for x in my_list]

64.7 ms ± 15.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Much faster!!

In [ ]:
zeros = np.zeros((10,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
ones = np.ones((10,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
empty = np.empty((10,5), dtype=int)
empty

array([[4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017

### Indexing and Slicing

In [ ]:
my_array = np.arange(15)

In [ ]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
my_array[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
my_array[9:11] = 34
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 34, 34, 11, 12, 13, 14])

Careful with slices as they point back to the orignial data! This is called a **view**.

In [ ]:
my_slice = my_array[0:2]
my_slice[0] = 101
my_array

array([101,   1,   2,   3,   4,   5,   6,   7,   8,  34,  34,  11,  12,
        13,  14])

In [ ]:
#can force a hard copy with .copy()
my_slice = my_array[0:2].copy()
my_slice[0] = 201
print(my_array)
print(my_slice)

[101   1   2   3   4   5   6   7   8  34  34  11  12  13  14]
[201   1]


In [ ]:
my_array[4:] = 9
my_array[:]

array([101,   1,   2,   3,   9,   9,   9,   9,   9,   9,   9,   9,   9,
         9,   9])

slicing 2d arrays

In [ ]:
A = np.array([[1, 1, 1],
              [6, 4, 5],
              [5, 2, 2]])

A_slice = A[:2,2:]
A_slice

array([[1],
       [5]])

### Boolean Indexing

In [3]:
animals = np.array(["dog", "cat", "mouse", "dog", "cat", "pig", "fish"])

In [4]:
rel_data = np.array([[5, 6], [9, 2], [3, 8], [7, 5], [3, 2], [-1, -40], [35, 42]])

In [5]:
rel_data.shape

(7, 2)

In [7]:
animals == "dog"

array([ True, False, False,  True, False, False, False])

In [9]:
animals != "dog"

array([False,  True,  True, False,  True,  True,  True])

In [ ]:
rel_data[animals != "dog",:1] = 54
rel_data

array([[  5,   6],
       [ 54,   2],
       [ 54,   8],
       [  7,   5],
       [ 54,   2],
       [ 54, -40],
       [ 54,  42]])

### Reshaping and Transposing

In [ ]:
my_reshape_array = np.arange(20).reshape((4, 5))
my_reshape_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
my_reshape_array.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])