In [3]:
import numpy as np
row_vector = np.array([1,2,3])
print("Row Vector:", row_vector)

Row Vector: [1 2 3]


In [4]:
column_vector = np.array([[1],[2],[3]])
print("Column Vector:", column_vector)

Column Vector: [[1]
 [2]
 [3]]


In [6]:
matrix_3x3 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
print("3x3 Matric:", matrix_3x3)

3x3 Matric: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("All elements in the matrix", matrix_3x3)

All elements in the matrix [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print("Element in second row, second column", matrix_3x3[1, 1])

Element in second row, second column 5


In [9]:
print("Element in first two rows and all columns", matrix_3x3[:2, :])

Element in first two rows and all columns [[1 2 3]
 [4 5 6]]


In [10]:
print("Element in last row", matrix_3x3[2, :])

Element in last row [7 8 9]


In [11]:
print("Element in last column", matrix_3x3[:, 2])

Element in last column [3 6 9]
