In [1]:
import numpy as np

#Operations on a 3x3 matrix
matrix_3x3 = np.array([[2, 4, 6], [12, 14, 16], [32, 34, 36]])
mean_3x3 = matrix_3x3.mean()  # Calculate mean of all elements
variance_3x3 = matrix_3x3.var()  # Calculate variance of all elements
std_dev_3x3 = matrix_3x3.std()  # Calculate standard deviation of all elements
mean_columns_3x3 = matrix_3x3.mean(axis=0)  # Calculate mean of each column

In [2]:
print("Task 1 Results:")
print("Mean:", mean_3x3)
print("Variance:", variance_3x3)
print("Standard Deviation:", std_dev_3x3)
print("Mean of each column:", mean_columns_3x3)

Task 1 Results:
Mean: 17.333333333333332
Variance: 158.22222222222223
Standard Deviation: 12.578641509408806
Mean of each column: [15.33333333 17.33333333 19.33333333]


In [3]:
matrix_4x3 = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45], [50, 55, 60]])
reshaped_2_6 = matrix_4x3.reshape(2, 6)  # Reshape the matrix to 2 rows and 6 columns
size_4x3 = matrix_4x3.size  # Get the total number of elements
reshaped_1_row = matrix_4x3.reshape(1, -1)  # Reshape to 1 row with as many columns as needed
transpose_4x3 = matrix_4x3.T  # Transpose the matrix
flattened_4x3 = matrix_4x3.flatten()  # Flatten the matrix to a 1D array
det_4x3 = np.linalg.det(matrix_4x3[:3, :3])  # Calculate determinant of the first 3x3 part
diagonal_4x3 = np.diagonal(matrix_4x3[:3, :3])  # Extract the main diagonal
diagonal_above_4x3 = np.diagonal(matrix_4x3[:3, :3], 1)  # Extract one above the main diagonal
diagonal_below_4x3 = np.diagonal(matrix_4x3[:3, :3], -1)  # Extract one below the main diagonal

In [4]:
print("\nTask 2 Results:")
print("Reshaped to 2x6:", reshaped_2_6)
print("Size of matrix:", size_4x3)
print("Reshaped to 1 row:", reshaped_1_row)
print("Transpose:", transpose_4x3)
print("Flattened:", flattened_4x3)
print("Determinant:", det_4x3)
print("Diagonal elements:", diagonal_4x3)
print("Diagonal above main:", diagonal_above_4x3)
print("Diagonal below main:", diagonal_below_4x3)



Task 2 Results:
Reshaped to 2x6: [[ 5 10 15 20 25 30]
 [35 40 45 50 55 60]]
Size of matrix: 12
Reshaped to 1 row: [[ 5 10 15 20 25 30 35 40 45 50 55 60]]
Transpose: [[ 5 20 35 50]
 [10 25 40 55]
 [15 30 45 60]]
Flattened: [ 5 10 15 20 25 30 35 40 45 50 55 60]
Determinant: -5.329070518200756e-13
Diagonal elements: [ 5 25 45]
Diagonal above main: [10 30]
Diagonal below main: [20 40]


In [5]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
addition_a_b = np.add(matrix_a, matrix_b)  # Add two matrices
subtraction_a_b = np.subtract(matrix_a, matrix_b)  # Subtract matrix_b from matrix_a
multiplication_a_b = np.dot(matrix_a, matrix_b)  # Multiply two matrices

In [6]:
print("\nTask 3 Results:")
print("Addition of A and B:", addition_a_b)
print("Subtraction of B from A:", subtraction_a_b)
print("Multiplication of A with B:", multiplication_a_b)


Task 3 Results:
Addition of A and B: [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction of B from A: [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Multiplication of A with B: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
